### ISSUE TITLE
Default launch options improvements & suggestions

### ISSUE THREAD

**Issue by Wiethoofd** [mkrl/cfgtf#11]
Certain defaults for the suggested launch options are **horrible** and should only be used in case the PC is an actual toaster and configs don't have the desired effects. And some additional Quality of Life launch option suggestions:

- DirectX 8 disables outlines, has certain hud issues
  - Default to 91 or 95 with option to pick 98 when a High Quality config is selected
- Remove `-noborder` when `-full` (fullscreen) is selected
- Replace `-sw` with `-window` for readability/clarity
  - For the Windowed selection optional `-x` & `-y` for position of the game window
- Optional `-vr`, `-console` `-nojoy`, `-threads <int>` and `-high` launch settings

**Comment by mkrl** [comment]
DX8 is intended to be used with Toaster and Stability configs. If you have an old PC, dx8 is beneficial. All the other configs change launch options automatically on select, so "Max FPS for High Quality PCs" is using 91, and Cinema config is using 98.

**Comment by Wiethoofd** [comment]
I had the _None_ base config selected, imo that should default to a minimum of 90 as `-dxlevel`

**Comment by mkrl** [comment]
Added some launch options now, dxlevel is now 90 by default as well.
