### ISSUE TITLE
Can't download config with custom hit/kill sounds in Firefox 52

### ISSUE THREAD

**Issue by Llewxamris** [mkrl/cfgtf#13]
Tested downloading the same config with Firefox 52 and Google Chrome 57. Downloading the script works fine in Chrome, but in Firefox this error is given on the page:
`Error: Ajax error for ../make/snd/Q3.wav : 206 Partial Content`
This is vanilla Firefox with all addons disabled.

**Comment by mkrl** [comment]
Should be fixed now

**Comment by Llewxamris** [comment]
Same error occurring in Firefox 53.0, no addons enabled. 
`Error: Ajax error for ../make/snd/funky.wav : 206 Partial Content`
Works fine in Google Chrome.

**Comment by mkrl** [comment]
Strange things are happening, it should be working, but it doesn't. I will take a look at this again.

**Comment by mkrl** [comment]
This might have been something to do with how Firefox caches HTML5 audio: https://bugzilla.mozilla.org/show_bug.cgi?id=874867 .

I'm not sure, it works on my local server but it does not work on the production site.

**Comment by xiyzzc** [comment]
I have this problem locally and can work around it by simply renaming the wav file extension to something else (I picked .wave), since the js renames it anyway. Not sure it will work on your server, but worth a try if you can't figure out a proper fix.

**Comment by mkrl** [comment]
This issue seems to be fixed in the latest update (Jekyll migration).
