### ISSUE TITLE
fastclass_.cfg not found.

### ISSUE THREAD

**Issue by Llewxamris** [mkrl/cfgtf#19]
Selecting the fastclass script causes a 404 error.
`Error: Ajax error for ../make/cfg/fastclass_.cfg : 404`
Figure it should point to either fastclass.cfg or fastclass_cs.cfg, but not something in between ;)

**Comment by mkrl** [comment]
Got the problem, thanks. Will fix very soon.

**Comment by mkrl** [comment]
Should be working now.
