### ISSUE TITLE
sv_downloadurl needs to be inside of quotes

### ISSUE THREAD

**Issue by BurningSmile** [mkrl/cfgtf#26]
I spent about 20 minutes tonight troubleshooting why I couldn't get fastdl to work with a Nginx webserver. It turns out cfg.tf does not put sv_downloadurl inside of a set of "". Not doing so causes the server to not download files properly and instead downloads .bsp's from the server directly as apposed to .bz2's from the webserver. 

Solution is to simply make it so that the default config has the variable like so
sv_downloadurl "ip-or-hostname/path/to/directory/before/maps"

instead of 
sv_downloadurl ip-or-hostname/path/to/directory/before/maps

**Comment by mkrl** [comment]
Woops, my bad. Thank you for the report, I will fix this as soon as I get back from my little vacation on Monday.

**Comment by mkrl** [comment]
The issue was resolved in https://github.com/mkrl/cfgtf/commit/6ef9f1c5382e2f6d09679ed3e19f206198205a7c
