### ISSUE TITLE
Weapon-specific crosshairs doesn't always make the script files. 

### ISSUE THREAD

**Issue by TheSarr** [mkrl/cfgtf#44]
So I've been trying to use the Weapon-specific crosshairs generator and it doesn't always create the script files for you to download. I did it yesterday and it didn't give me the files at all and today it did once but after trying again it failed to do so.

**Comment by mkrl** [comment]
Fixed in https://github.com/mkrl/cfgtf/commit/a958c07df930390a66536ac6b1d206b1bbe5e6f4
