### ISSUE TITLE
On Mac, Zip File is Corrupted

### ISSUE THREAD

**Issue by KuruKuru3532** [mkrl/cfgtf#47]
I tried clicking on the "Generate Config" button, but when I tried to expand the Zip file, an error shows up on the screen. 
![screen shot 2018-05-13 at 11 24 21 pm](https://user-images.githubusercontent.com/32959775/39981291-d1c20fee-5704-11e8-9b78-6a52c58ec440.png)

This is probably because of it being corrupted. Or it might just not be meant for Mac players. Who knows.

**Comment by TheRealDwapDwag** [comment]
Download WinZip and open cfg folder and save to mac, i think the custom folder is f*%&ing it up

**Comment by InsightAbe05** [comment]
An easy google search would have helped:
https://www.tourvista.com/blog/2012/05/for-mac-users-only-how-to-unzip-a-file-fixing-mac-error-1-operation-not-permitted/
There you go.
