### ISSUE TITLE
"Connection settings" article is a dead link

### ISSUE THREAD

**Issue by sapphonie** [mkrl/cfgtf#5]
![image](https://cloud.githubusercontent.com/assets/15315481/24394143/cd2b7244-1368-11e7-840a-2ce6d40766fd.png)
![image](https://cloud.githubusercontent.com/assets/15315481/24394156/d8defcfa-1368-11e7-8747-6efd04c8b99b.png)
https://dl.dropboxusercontent.com/u/1811521/interp.html

**Comment by mkrl** [comment]
Thanks, looks like the original author have removed the file from public. I think I have a saved copy on my work PC, will take a look soon and push it with next update.

**Comment by mkrl** [comment]
Should be fixed now, rehosted an article on my site. Thanks for reporting!
