### ISSUE TITLE
CFG Crosshair Picker Tool Issue

### ISSUE THREAD

**Issue by InsightAbe05** [mkrl/cfgtf#54]
The weapons that have a explosions are broken, if you choose a custom explosion it's fine, but if it's the default explosion, it doesnt give any scripts. Please fix i do like the default explosions. I tried it 100s of times, switching from chrome to safari, trying other computers and it still doesn't work, it's a very annoying issue.

**Comment by mkrl** [comment]
Thanks, yes, I'm aware of this problem. I'll try to fix this as soon as I have some spare time

**Comment by InsightAbe05** [comment]
yay!  let me know when its patched!
