### ISSUE TITLE
No crosshairs for rocketlaunchers?

### ISSUE THREAD

**Issue by insomniaa1** [mkrl/cfgtf#56]
So, when I downloaded the weapon especific crosshairs, stuff like tf_weapon_rocketlaucher.txt are missing, the weapons I found missing are : The Rocketlauncher, Cowmangler 5000, Direct Hit, Airstrike, Beggar's Bazooka and The Original, basically all the soldier primaries

**Comment by InsightAbe05** [comment]
same here

**Comment by mkrl** [comment]
Duplicate of https://github.com/mkrl/cfgtf/issues/44
