### ISSUE TITLE
Setting resetting

### ISSUE THREAD

**Issue by AGuyWithAnIssue** [mkrl/cfgtf#7]
So when I open the game and make some settings, i restart the game and the settings are gone. 
Im using the toaster config btw. What can I do?

**Comment by mkrl** [comment]
If you have any custom configs (including this one), they will overwrite your settings every time you launch the game. If you want to change any settings, put corresponding commands in your "Custom binds" section when generating a config. You can also change settings in settings.cfg / binds.cfg in your existing config. Sadly, currently it is not possible to save them.

**Comment by AGuyWithAnIssue** [comment]
Ok. Thanks!
